package com.modragon.ace.server.utility.constants;


public enum ErrorCode {
	
	SYSTEM_ERROR(500, "INTERNAL_SERVER_ERROR", "服务器内部错误"),
	
	ACCOUNT_NOT_EXIST(401,"ACCOUNT_NOT_EXIST", "账号不存在"),
	PASSWORD_NOT_CORRECT(401,"PASSWORD_NOT_CORRECT", "密码不正确"),
	PASSWORD_NOT_NULL(401,"PASSWORD_NOT_CORRECT", "密码不能为空"),
	PASSWORD_SAME(400,"PASSWORD_SAME", "新密码与原密码相同"),
	LOGIN_FAILURE(500,"LOGIN_FAILURE", "登录失败"),
	LOGOUT_FAILURE(500,"LOGOUT_FAILURE","退出失败"),
	UPLOAD_FAILURE(500,"UPLOAD_FAILURE","文件上传失败"),
	CHANGE_HEADIMG_FAILURE(500,"CHANGE_HEADIMG_FAILURE","修改用户头像失败"),
	MOD_ZONEICON_FAILURE(500,"MOD_ZONEICON_FAILURE","修改用户空间壁纸失败"),
	PHONE_NUMBER_FORMAT_INVALID(400,"INVALID_ARGUMENT","手机号码格式不正确"),
	INVALID_ARGUMENT(400,"INVALID_ARGUMENT","输入参数格式不正确"),
	REQUIRE_ARGUMENT(400,"REQUIRE_ARGUMENT","缺少参数"),
	ARGUMENT_NOT_CORRECT(400,"ARGUMENT_NOT_CORRECT","参数不正确"),
	OPENID_NOT_NULL(401,"OPENID_NOT_NULL", "微信openId不能为空"),
	
	USERID_NOT_NULL(400,"USERID_NOT_NULL","用户ID不为空"),
	SCHOOLID_NOT_NUll(400,"SCHOOLID_NOT_NUll","学校ID不为空"),
	CLASSID_NOT_NUll(400,"CLASSID_NOT_NUll","班级ID不为空"),
	TESTID_NOT_NULL(400,"TESTID_NOT_NULL","用户ID不为空"),
	SCHOOLID_NOT_EXIST(400,"SCHOOLID_NOT_EXIST", "学校ID不存在"),
	MSGID_NOT_NULL(400,"MSGID_NOT_NULL","消息ID不为空"),
	COURSEID_NOT_NULL(400,"COURSEID_NOT_NULL","科目ID不为空"),
	UINTID_NOT_NULL(400,"UINTID_NOT_NULL","单元ID不为空"),
	SUBJECTID_NOT_NULL(400,"SUBJECTID_NOT_NULL","科目分类ID不为空"),
	LESSIONID_NOT_NULL(400,"LESSIONID_NOT_NULL","课节ID不能为空"),
	ATTCHID_NOT_NULL(400,"ATTCHID_NOT_NULL","课件ID不能为空"),
	STEPS_NOT_NULL(400,"STEPS_NOT_NULL","课件步骤ID不能为空"),
	ATTCHNAME_NOT_NULL(400,"ATTCHID_NOT_NULL","课件名称不能为空"),
	STEPTITLE_NOT_NULL(400,"STEPTITLE_NOT_NULL","步骤标题不能为空"),
	STEPTYPE_NOT_NULL(400,"STEPTYPE_NOT_NULL","步骤类型不能为空"),
	FUJIAN_NOT_NULL(400,"FUJIAN_NOT_NULL","附件不能为空"),
	CONTENTS_NOT_NULL(400,"CONTENTS_NOT_NULL","内容不为空"),
	REPLYIDS_NOT_NULL(400,"REPLYIDS_NOT_NULL","提问对象ID不能为空"),
	GRADID_NOT_NULL(400,"GRADID_NOT_NULL","年级ID不为空"),
	ATTCH_NOT_NULL(400,"ATTCH_NOT_NULL","附件不能为空"),
	ATTCHIDS_NOT_NULL(400,"ATTCHIDS_NOT_NULL","提问附件ID不能为空"),
	QUESTID_NOT_NULL(400,"QUESTID_NOT_NULL","提问ID不为空"),
	USERNAME_NOT_NULL(400,"USERNAME_NOT_NULL","姓名不为空"),
	SEX_NOT_NULL(400,"SEX_NOT_NULL","性别不为空"),
	MOBILE_PGONE_NOT_NULL(400,"MOBILE_PGONE_NOT_NULL","联系电话不为空"),
	ADDRESS_NOT_NULL(400,"ADDRESS_NOT_NULL","联系地址不为空"),
	REPLYTYPE_NOT_NULL(400,"REPLYTYPE_NOT_NULL","回复类型不能为空"),
	VIDEOID_NOT_NULL(400,"VIDEOID_NOT_NULL","视频ID不为空"),
	COMMENT_CONTENT_NOT_NULL(400,"COMMENT_CONTENT_NOT_NULL","评论内容不能为空"),
	TERMID_NOT_NULL(400,"TERMID_NOT_NULL","学期ID不能为空"),
	ANSWER_CONTENT_NOT_NULL(400,"ANSWER_CONTENT_NOT_NULL","回复内容不能为空"),
	STUDENT_NOT_NULL(400,"STUDENT_NOT_NULL","学生ID不能为空"),
	//Account
	USER_NOT_EXIST(400,"USER_NOT_EXIST", "用户不存在"),
	MSG_NOT_EXIST(400,"MSG_NOT_EXIST","该消息不存在，或已被删除"),
	MOD_USERINFO_FAILURE(400,"MOD_USERINFO_FAILURE","修改个人信息失败"),
	GET_MSGWDLIST_ROLE_FAILURE(400,"GET_MSGWDLIST_ROLE_FAILURE","获取个人消息列表失败"),
	GET_MSGDETAIL_ROLE_FAILURE(400,"GET_MSGDETAIL_ROLE_FAILURE","获取个人消息详情失败"),
	DELETE_ROLE_FAILURE(400,"DELETE_ROLE_FAILURE","个人消息删除失败"),
	MOD_PASSWORD_FAILURE(400,"MOD_PASSWORD_FAILURE","修改密码失败"),
	MOD_MAGFLG_FAILURE(400,"MOD_MAGFLG_FAILURE","更新消息状态失败,该消息不存在或已被删除"),
	//Student
	QUEST_NOT_EXIST(400,"QUEST_NOT_EXIST","该提问不存在，或已被删除"),
	SUBQUEST_ROLE_FAILURE(400,"SUBQUEST_ROLE_FAILURE","我要提问失败"),
	GET_TEACHERS_ROLES_FAILURE(400,"GET_TEACHERS_ROLES_FAILURE","获取选择老师列表失败"),
	GET_QUESTLIST_ROLES_FAILURE(400,"GET_QUESTLIST_ROLES_FAILURE","获取提问列表失败"),
	GET_QUESTDETAIL_ROLES_FAILURE(400,"GET_QUESTDETAIL_ROLES_FAILURE","获取提问详情失败"),
	GET_DATALIST_FAILURE(400,"GET_DATALIST_FAILURE","获取资料列表失败"),
	//Exam
	GET_EXCRCISES_FAILURE(400,"GET_EXCRCISES_FAILURE","获取作业列表失败"),
	GET_EXAMLIST_FAILURE(400,"GET_EXAMLIST_FAILURE","获取课程试题列表失败"),
	GET_ANSWERLIST_FAILURE(400,"GET_ANSWERLIST_FAILURE","获取试卷答题卡失败"),
	GET_EXAMPREVIEW_FAILURE(400,"GET_EXAMPREVIEW_FAILURE","获取试卷答题卡预览失败"),
	POST_STARTEXAM_FAILURE(400,"POST_STARTEXAM_FAILURE","开始答题失败"),
	GET_QUEST_QUESTION(400,"GET_QUEST_QUESTION","获取获取答题信息失败"),
	POST_ANSER_FAILURE(400,"POST_ANSER_FAILURE","试题答案提交"),
	POST_EXAM_FAILURE(400,"POST_EXAM_FAILURE","试卷提交失败"),
	GET_ANSWERRESULT_FAILURE(400,"GET_ANSWERRESULT_FAILURE","获取试题答题结果失败"),
	GET_CRSTESTANSWER_FAILURE(400,"GET_CRSTESTANSWER_FAILURE","获取答题错误解析失败"),
	//Video
	UPDATE_VIDEODOWNLOAD_FAILURE(400,"UPDATE_VIDEODOWNLOAD_FAILURE","视频下载次数更新失败"),
	UPDATE_VIDEOCLICKCNT_FAILURE(400,"UPDATE_VIDEOCLICKCNT_FAILURE","视频播放次数更新失败"),
	GET_VIDEOLIST_FAILURE(400,"GET_VIDEOLIST_FAILURE","获取视频列表失败"),
	GET_VIDEODETAIL_FAILURE(400,"GET_VIDEODETAIL_FAILURE","获取视频详情失败"),
	GET_COMMENT_FAILURE(400,"GET_COMMENT_FAILURE","获取视频评论失败"),
	SHARE_VIDEO_FAILURE(400,"GET_COMMENT_FAILURE","分享视频失败"),
	SHARE_PPT_FAILURE(400,"GET_COMMENT_FAILURE","分享资料失败"),
	//Exam
	QUESTION_NOT_EXIST(400,"QUESTION_NOT_EXIST", "试题不存在"),
	EXAMID_NOT_NUll(400,"EXAMID_NOT_NUll", "考卷ID不为空"),
	POSTANSWER_FAILURE(400,"POSTANSWER_FAILURE","答案提问失败"),
	TEST_ANSWER_NOT_NULL(400,"TEST_ANSWER_NOT_NULL","答案不为空"),
	TEST_TYPE_NOT_NULL(400,"TEST_TYPE_NOT_NULL","题型不为空"),
	TEST_STATUS_NOT_NULL(400,"TEST_STATUS_NOT_NULL","试题状态不为空"),
	BE_ASSIGN_NOT_NULL(400,"BE_ASSIGN_NOT_NULL","分享班级不为空"),
	SUB_EXAM_FAILURE(400,"SUB_EXAM_FAILURE","试卷添加失败"),
	ASSIGN_EXAM_FAILURE(400,"ASSIGN_EXAM_FAILURE","试卷分享失败"),
	//sendMsg
	MSG_TITLE_NOT_NULL(400,"MSG_TITLE_NOT_NULL", "消息标题不能为空"),
	TO_CLASS_NOT_NULL(400,"TO_CLASS_NOT_NULL", "收件人不能为空"),
	SEND_MSG_FAILURE(400,"SEND_MSG_FAILURE", "消息发送失败"),
	GET_MSGLIST_FAILURE(400,"GET_MSGLIST_FAILURE", "消息查询失败"),
	GET_LIMITS_FAILURE(400,"GET_LIMITS_FAILURE", "老师权限下的课程、年级、班级查询失败"),
	GET_TERMS_FAILURE(400,"GET_TERMS_FAILURE", "查询学期列表失败"),
	GET_CLASS_STUDENTS_FAILURE(400,"GET_CLASS_STUDENTS_FAILURE", "班级学生列表查询失败"),
	GET_STUQUEST_FAILURE(400,"GET_STUQUEST_FAILURE", "指定学生问题列表查询失败"),
	//LESSONES_ATTCH
	GET_ATTCHLIST_FAILURE(400,"GET_ATTCHLIST_FAILURE","获取课件列表失败"),
	GET_STEPS_FAILURE(400,"GET_ATTCHLIST_FAILURE","获取课件步骤列表失败"),
	GET_ATTCH_FAILURE(400,"GET_ATTCH_FAILURE","获取课件详情失败"),
	GET_STEPINFO_FAILURE(400,"GET_STEPINFO_FAILURE","获取课件步骤详情失败"),
	ADD_ATTCH_FAILURE(400,"ADD_ATTCH_FAILURE","课件新增失败"),
	MOD_ATTCH_FAILURE(400,"MOD_ATTCH_FAILURE","课件修改失败"),
	DEL_ATTCH_FAILURE(400,"DEL_ATTCH_FAILURE","课件删除失败"),
	ADD_STEPS_FAILURE(400,"ADD_STEPS_FAILURE","课件步骤新增失败"),
	MOD_STEPS_FAILURE(400,"MOD_ATTCH_FAILURE","课件步骤修改失败"),
	DEL_STEPS_FAILURE(400,"DEL_STEPS_FAILURE","课件步骤删除失败"),
	//schedule
	START_TIME_NOT_NULL(400,"START_TIME_NOT_NULL", "开始时间不能为空"),
	END_TIME_NOT_NULL(400,"END_TIME_NOT_NULL", "结束时间不能为空"),
	GET_SCHEDULE_FAILURE(400,"GET_SCHEDULE_FAILURE", "课程表查询失败"),
	DEL_EXAM_FAILURE(400,"DEL_EXAM_FAILURE", "试卷删除失败"),
	MOD_EXAM_FAILURE(400,"MOD_EXAM_FAILURE", "试卷编辑失败"),
	GET_CLASSEXAMABOUT_FAILURE(400,"GET_CLASSEXAMABOUT_FAILURE", "查看班级考试情况失败"), 
	CORRECT_TEST_FAILURE(400,"CORRECT_TEST_FAILURE", "试卷批改失败"),
	GET_CLASSLIST_FAILURE(400,"GET_CLASSLIST_FAILURE", "教师试卷/作业批改选择班级列表数据获取失败"),
	EXAMAVG_SCORELIST_FAILURE(400,"EXAMAVG_SCORELIST_FAILURE", "试卷成绩管理列表数据获取失败"),
	EXAM_STUDENT_SCORELIST_FAILURE(400,"EXAM_STUDENT_SCORELIST_FAILURE", "试卷学生成绩数据获取失败"),
	EXAM_CLASSAVG_SCORELIST_FAILURE(400,"EXAM_STUDENT_SCORELIST_FAILURE", "试卷班级成绩列表数据获取失败"), 
	OPTIONS_LENGTH_NOTEQ(400,"OPTIONS_LENGTH_NOTEQ", "添加试题失败"),
	ADD_TEST_FAILURE(400,"OPTIONS_LENGTH_NOTEQ", "添加试题失败"),
	MOD_TEST_FAILURE(400,"MOD_TEST_FAILURE", "试题编辑失败"),
	DEL_TEST_FAILURE(400,"DEL_TEST_FAILURE", "试题删除失败"),
//	GET_CLASSEXAMABOUT_FAILURE(400,"MOD_EXAM_FAILURE", "查看班级考试情况失败"),
	//upload
	UPLOAD_RESOURSE_FAILURE(400,"UPLOAD_RESOURSE_FAILURE", "资源上传失败"),
	GET_QRYTEACHCLASSESINFO_FAILURE(400,"GET_QRYTEACHCLASSESINFO_FAILURE", "获取班级列表失败"),

	GET_QRYUSERINFO_FAILURE(400,"GET_QRYUSERINFO_FAILURE", "获取教师个人信息失败"),
	UPLOAD_FILE_FAILURE(400,"UPLOAD_FILE_FAILURE", "文件上传失败"),
	UPDATE_HISCHOOSE_FAILURE(400,"UPDATE_HISCHOOSE_FAILURE", "更新历史选择失败"),
	DEL_VIDEO_FAILURE(400,"DEL_VIDEO_FAILURE", "视频删除失败，该视频不存在或已被删除"),
	
	//curse msg
	MODEL_LIST_FAILURE(400,"MODEL_LIST_FAILURE","获取模块列表失败"),
	GREAD_LIST_FAILURE(400,"GREAD_LIST_FAILURE","获取年段列表失败"),
	CALATOG_LIST_FAILURE(400,"CALATOG_LIST_FAILURE","获取科目列表失败"),
	LESSON_LIST_FAILURE(400,"CALATOG_LIST_FAILURE","获取单元列表失败"),
	ADD_UNIT_FAILURE(400,"ADD_UNIT_FAILURE","新增单元失败"),
	ADD_CLASSCOURSES_FAILURE(400,"ADD_CLASSCOURSES_FAILURE","保存课程表失败"),
	ADD_PIC_FAILURE(400,"ADD_PIC_FAILURE","新增轮播图成功"),
	MOD_PIC_FAILURE(400,"MOD_PIC_FAILURE","修改轮播图成功"),
	MOD_UNIT_FAILURE(400,"MOD_UNIT_FAILURE","修改单元失败"),
	DEL_UNIT_FAILURE(400,"DEL_UNIT_FAILURE","删除单元失败"),
	DEL_PIC_FAILURE(400,"DEL_PIC_FAILURE","删除轮播图失败"),
	MOD_PSD_FAILURE(400,"DEL_UNIT_FAILURE","修改密码失败"),
	ADD_LESSON_FAILURE(400,"ADD_UNIT_FAILURE","新增课节失败"),
	MOD_LESSON_FAILURE(400,"MOD_UNIT_FAILURE","修改课节失败"),
	DEL_LESSON_FAILURE(400,"DEL_UNIT_FAILURE","删除课节失败"),
	DEL_COURSE_FAILURE(400,"DEL_COURSE_FAILURE","删除科目失败"),
	GET_SYS_PARAMETER_FAILURE(400,"GET_QRYUSERINFO_FAILURE", "获取系统变量失败"),
	GET_EXAM_LIST_FAILURE(400,"GET_EXAM_LIST_FAILURE", "获取试卷列表失败"),
	GET_EXAM_TEST_LIST_FAILURE(400,"GET_EXAM_TEST_LIST_FAILURE", "获取试题列表失败"),
	GET_STUDENT_EXAMABOUT_FAILURE(400,"GET_STUDENT_EXAMABOUT_FAILURE", "获取学生考试试卷列表失败"), 
	CORR_EXAM_SUTDENTLIST_FAILURE(400,"CORR_EXAM_SUTDENTLIST_FAILURE", "获取批改试卷学生列表失败"),
	ASWER_QUESTION_FAILURE(400,"ASWER_QUESTION_FAILURE", "回复问题失败,该提问不存在或已被删除"),
	UPDATE_SCHOOL_FAILURE(400,"UPDATE_SCHOOL_FAILURE","修改学校信息失败"), 
	COURSE_LIST_FAILURE(400,"COURSE_LIST_FAILURE","获取科目信息失败"),
	ADD_COURSE_FAILURE(400,"ADD_COURSE_FAILURE","添加科目失败"), 
	STUDENT_NOT_NUll(400,"STUDENT_NOT_NUll","获取学生信息失败"),
	PIC_NOT_NUll(400,"STUDENT_NOT_NUll","获取轮播图失败"),
	EXAM_COUNTE_FAILURE(400,"EXAM_COUNTE_FAILURE"," 获取班级试卷答题情况失败"),
	NO_T_HOME_IMAGES(400,"NO_T_HOME_IMAGES"," 获取轮播图片失败"),
	UPDATE_ATTCH_FAILURE(400,"UPDATE_ATTCH_FAILURE","修改失败"),
	UPDATE_ATTCH_ID_IS_NULL(400,"UPDATE_ATTCH_ID_IS_NULL","修改的附件id未空"), 
	SEND_OBJECT_NOT_NULL(400,"SEND_OBJECT_NOT_NULL","消息发送对象类型不能为空");

    // 成员变量
	private int httpStatus;//http状态码--默认200
    private String code;//错误信息编码
    private String message;//错误信息内容
    private int res_code;//结果状态码(按http状态标准填写)

    // 构造方法
    private ErrorCode(int resCode, String code, String message) {
    	this.setHttpStatus(200);
    	this.setRes_code(resCode);
        this.setCode(code);
		this.setMessage(message);
    }
    private ErrorCode() {
    	this.setHttpStatus(httpStatus);
        this.setCode(code);
		this.setMessage(message);
    }
	public int getHttpStatus() {
		return httpStatus;
	}

	public void setHttpStatus(int httpStatus) {
		this.httpStatus = httpStatus;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public int getRes_code() {
		return res_code;
	}

	public void setRes_code(int res_code) {
		this.res_code = res_code;
	}

}
